export * from "./Footer";
export * from "./Header";
export * from "./Clientes";
export * from "./Contactanos";
export * from "./Equipo";
export * from "./Inicio";
export * from "./Portafolio";
export * from "./Servicios";
export * from "./Blog";